// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gaipouqrcrirsuhtnnuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhaXBvdXFyY3JpcnN1aHRubnV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1OTk0MTEsImV4cCI6MjA3MTE3NTQxMX0.J16WlLbQl2_gesY-OgASpxQq20uNdPQ9WXwyXpI6xYg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});